name: Daily Trivy Scan and SBOM Generation

on:
  schedule:
    - cron: '0 0 * * *'  # Run at 12am UTC daily
  workflow_dispatch:  # Allow manual triggering

jobs:
  scan:
    name: Trivy Scan and SBOM
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Generate SBOM
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          format: 'cyclonedx'
          output: 'sbom.json'

      - name: Upload SBOM to GitHub Dependency Graph
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/dependency-graph/sbom \
          -F sbom=@sbom.json
