name: PR Security Scan
on:
  pull_request:

jobs:
  scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'json'
          output: 'trivy-results.json'
          severity: 'HIGH,CRITICAL'

      - name: Post PR comment
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const results = JSON.parse(fs.readFileSync('trivy-results.json', 'utf8'));
            
            let comment = '## Trivy Security Scan Results\n\n';
            let vulnerabilities = results.Results.flatMap(r => r.Vulnerabilities || []);
            
            if (vulnerabilities.length === 0) {
              comment += 'No high or critical vulnerabilities found.';
            } else {
              comment += `${vulnerabilities.length} high or critical vulnerabilities found:\n\n`;
              vulnerabilities.forEach(vuln => {
                comment += `- **${vuln.Severity}**: ${vuln.VulnerabilityID} in ${vuln.PkgName}\n`;
                comment += `  Description: ${vuln.Title}\n`;
                comment += `  Installed Version: ${vuln.InstalledVersion}\n`;
                comment += `  Fixed Version: ${vuln.FixedVersion || 'Not available'}\n\n`;
              });
            }
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: comment
            });
