name: Container Security Scan
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build the Docker image
        run: docker build . -t appwrite_image:latest
      - name: Save Docker image
        run: docker save appwrite_image:latest > image.tar
      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

  scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image
      - name: Load Docker image
        run: docker load < image.tar
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'appwrite_image:latest'
          format: 'table'
          output: 'trivy-results.txt'
          exit-code: '1'
          ignore-unfixed: 'false'
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-results.txt
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

  comment-pr:
    needs: scan
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Download scan results
        uses: actions/download-artifact@v4
        with:
          name: trivy-results
      - name: Comment PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs')
            const results = fs.readFileSync('trivy-results.txt', 'utf8')
            const commentBody = `## Trivy Scan Results

            The following vulnerabilities were found:

            \`\`\`
            ${results}
            \`\`\`

            Please address these vulnerabilities before merging.`
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            })
