name: Container Security Scan
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build the Docker image
        run: docker build . -t appwrite_image:latest
      - name: Save Docker image
        run: docker save appwrite_image:latest > image.tar
      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

  scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image
      - name: Load Docker image
        run: docker load < image.tar
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'appwrite_image:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0'
          ignore-unfixed: 'false'
          severity: 'CRITICAL,HIGH'
          ignorefile: '.trivyignore'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
      - name: Generate HTML report
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/root/ aquasec/trivy:latest image --format template --template "@/contrib/html.tpl" -o /root/trivy-report.html appwrite_image:latest
      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Trivy-Scan-Report
          path: trivy-report.html

  deploy:
    needs: scan
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Download HTML report
        uses: actions/download-artifact@v4
        with:
          name: Trivy-Scan-Report
      - name: Create a GitHub Pages redirect file
        run: echo "<meta http-equiv='refresh' content='0; url=trivy-report.html'>" > index.html
      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
